#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
    ln -s /usr/lib/moduloais/moduloais /usr/bin/moduloais
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/moduloais.service ]; then
			rm /etc/systemd/system/moduloais.service /usr/lib/systemd/system/moduloais.service /usr/lib/systemd/user/moduloais.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/moduloais/files/systemd/moduloais.service /usr/lib/systemd/system/moduloais.service
		# try fix error in Ubuntu 18.04
		# Failed to reload moduloais.service: Unit moduloais.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/moduloais.service:10: Executable path is not absolute: pkill -f "moduloais --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/moduloais.service
		fi
		systemctl daemon-reload
		systemctl enable moduloais
		systemctl start moduloais
	fi
fi
